name: Run Selenium Tests and Deploy Allure Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Selenium Tests
      run: pytest --alluredir=reports

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        curl -sSL https://github.com/allure-framework/allure2/releases/download/2.22.5/allure-2.22.5.tgz | tar -xz
        sudo mv allure-2.22.5 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate Static Allure Report
      run: |
        allure generate reports -o allure-report --clean

    - name: Upload Allure Report to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ALLURE_BUCKET_NAME: ${{ secrets.ALLURE_BUCKET_NAME }}
      run: |
        aws s3 sync allure-report/ s3://$ALLURE_BUCKET_NAME/ --acl public-read --delete

    - name: Display Allure Report URL
      run: echo "Allure Report available at: http://${{ secrets.ALLURE_BUCKET_NAME }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com/"